name: Build Windows Executable

on:
  push:
    branches: [ build-github-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install MinGW
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH
          echo "C:\tools\mingw64\bin" >> $env:GITHUB_PATH
      - name: Run build script
        run: .\windows_build.bat
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: *.exe
