name: Build Mac Binary

on:
  push:
    branches: [ build-github-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update homebrew
        run: brew update
      - name: Install Dependencies
        run: brew install bear assimp
      - name: Verify installation
        run: |
          echo "LDFLAGS=-L$(brew --prefix assimp)/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix assimp)/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix assimp)/lib/pkgconfig" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$(brew --prefix assimp)/lib" >> $GITHUB_ENV
          echo $LDFLAGS
          echo $CPPFLAGS
          echo $PKG_CONFIG_PATH
          bear --version
          brew --prefix assimp
      - name: Verify working directory
        run: ls
      - name: Run build script
        run: |
          chmod +x mac_build.sh
          ./mac_build.sh
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: macOS-binary
          path: |
            3dco
